### ISSUE TITLE
발표 후 남은 이슈

### ISSUE THREAD

**Issue by ekgus9701** [Blueming-PDA/Blueming#101]
- [ ] 푸터에 가려지는 부분 수정
- [ ] 공지사항 댓글 안달리는 문제 수정
- [ ] 헤더 문구 변경하는 부분 수정
- [ ] 가입 페이지 상단 헤더 디자인 수정
- [ ] 게시판 흰 배경에 그림자 추가
- [x] 리드미 슬로건 삭제
- [ ] 회원가입 인증(중복된 ID 처리 등)
- [ ] 시연 영상 찍어서 리드미에 추가
- [ ] 반응형 UI 추가
- [ ] ERD 수정 후 리드미에 추가

**Comment by seohee99** [comment]
- [ ] ~~님의 화면을 보고 있습니다. 수정

**Comment by ekgus9701** [comment]
Client, Server 레포지토리로 이관하였습니다.
