### ISSUE TITLE
구현 및 문서 작업 남은 태스크 관리

### ISSUE THREAD

**Issue by lvolzdev** [Blueming-PDA/Blueming#85]
내일 발표 (2024.02.29 10:00) 전까지 완료해야 할 태스크 관리
각자 진행 상황 공유하기 위해 완료한 태스크 체크 부탁드립니다 ~!
<br />

## @allllfo 
- 로그인/회원가입
    - [x]  **로그인 페이지 img 안 뜨는 거 수정**
    - [x]  **회원가입 페이지 img 안 뜨는 거 수정**
    - [x]  **회원가입 페이지 placeholder 문구 변경 (nickname → name 변경)**
    - [x]  **‘이미 로그인되어 있습니다’ 알럿창 잠시 막아두기**
- 마이페이지
    - [x]  UI 수정
- 헤더
    - [x]  로고 누르면 메인 화면으로 이동하게끔
- 문서
    - [x]  각자 역할 작성
    - [x]  **핵심 기능 소개**

## @ekgus9701 
- 질문하기 기능 (학생)
    - [x]  **(style) 질문하기 모달창 디자인 UI**
        - [x]  **중앙 정렬**
        - [x]  **질문을 입력할게요. 버튼 누르면 동일 내용 반복 나옴.**
- 게시판
    - [x]  게시판 작성 페이지 내 ‘태그를 선택해주세요’ 문구 추가 (조그맣게)
    - [x]  과제함 ← admin은 모든 과제 볼 수 있게 기능 추가 필요.
- 헤더 공유문구창
    - [x]  **헤더 공유문구창 가로길이 늘리기**
    - [x]  **로직 변경 → DB저장**
- 문서
    - [x]  각자 역할 작성
    - [x]  **프로젝트 구조 아키텍처**
    - [x]  **케이스스터디 정리**

## @seohee99 
- 질문보기 기능 (선생님)
    - [x]  **모달창 자체를 중앙 배치 (위치 변경)**
    - [x]  **UI (알림보기 부분)**
    - [x]  **오른쪽 하단 알림창 크기, 안에 내용 배치, 색상 변경 ***
- 화면공유하기/화면공유 보기 기능 - 서희
    - [x]  링크 입력되지 않은 경우 ‘화면공유 보기’ 클릭 시 → 알럿창 해놨는데 안 뜸. 확인 필요.
    - [x]  **누구의 링크를 공유중입니다. 이런 문구 띄우기.**
- 문서
    - [x]  각자 역할 작성
    - [x]  **케이스스터디 정리**

## @lvolzdev 
- 메인페이지
    - [x]  **커리큘럼 데이터 json으로 넣기**
    - [x]  **옆으로 넘길 수 있게끔 부트스트랩 추가 (다음주 커리큘럼 보기 가능)**
    - [x] 주별 달력 hover 효과
    - [x] 전체적인 UI (배경색 및 컴포넌트 위치 변경)
- 배포
    - [x]  **CICD**
- 문서
    - [x]  리드미 틀 작성
    - [x]  각자 역할 작성
    - [x]  **서비스 소개 (기대효과, 왜 선정?)**
    - [x]  **케이스스터디 정리**

**Comment by seohee99** [comment]
@ekgus9701 질문 유형에 "다시 설명해 주세요" 하나만 추가해주세요!!

**Comment by ekgus9701** [comment]
> @ekgus9701 질문 유형에 "다시 설명해 주세요" 하나만 추가해주세요!!

-> 추가했습니다.
